filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, src/Utils/Collection.php, src/Utils/ArrayHelper.php]

checks:
    php:
        code_rating: true
        duplication: false
tools:
    php_sim: false
    php_cpd: false
