filter:
    paths: [src/*]
    excluded_paths: [bin/*, spec/*, tests/*, stub/*, coverage/*]
checks:
    php:
        code_rating: true
tools:
    external_code_coverage: true
    external_code_coverage:
        runs: 3
        timeout: 1200
